version: '3.8'

services:
  api:
    build: .
    container_name: hyperblock-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB_NAME=hyperblock
      - DEBUG=True
      - SECRET_KEY=your_secret_key_here
    depends_on:
      - mongo
    networks:
      - hyperblock-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:latest
    container_name: hyperblock-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - hyperblock-network

networks:
  hyperblock-network:
    driver: bridge

volumes:
  mongo-data: